FROM python:3.11-alpine

RUN apk add --no-cache \
    bash \
    wireguard-tools \
    openssh-client

WORKDIR /app

COPY ./scripts/ /app/
COPY default.sh /app/
COPY ansible.cfg /app/

RUN chmod +x /app/*.sh
